; ZX Game Mappings Spec v0.0 - based on previous work by Arda
; - rlyeh, public domain.
;
; ';' for comments.
; ' ' and '\t' as whitespaces.
; '\n' and/or '\r' as linefeeds.
;
; VKs
; ===
;
; Keys in the spec can be one of the following VKs:
;   0123456789 ABCDEFGHIJKLMNOPQRSTUVWXYZ
;     _(Space) !(Enter) $(Symb) ^(Caps)
;       -(NoKey) *(AnyNonAssignedKey)
;
; A:B:C is a sequence of separated A B C keypresses.
; A+B+C is a chord of simultaneous A+B+C keypress.
;
; Format
; ======
;
; gameName[zxdbId]={FISHCAKEDRQ..}  {..}  {UDLRF..} {UDLRF..} {...}+
; \--------------/ \-------------/ \----/ \-------/ \-------/
;    game info       common keys    extra  mapping1  mapping2  ...
;
; Common block: omitted if leading '-' is found.
; Unordered list of Action+VK pairs, as follows:
; F = [F]uller
; I = [I]nterface2
; S = [S]inclair1
; H = [H]old
; C = [C]ursor
; A = [A]bort
; K = [K]empston
; E = k[E]eyboard
; D = [D]efineKeys
; R = [R]esume
; Q = [Q]uickstart (while in main menu)
;
; Extra block: omitted if leading '-' is found.
; Unordered: AdditionalKey1,AdditionalKey2,AdditionalKey3...
;
; Mapping block(s): omitted if leading '-' is found.
; Order matters: Up,Down,Left,Right,Fire1,Fire2,Fire3...
;

AntAttack[210]=A1 0P!_ V-M$SC
AticAtac[9305]=E1K2C3H_R_Q0 456 REQWTZ
BackToSkool[362]=Q_ - QAOPFHCDGJMRSTW
BeachHead[481]=HHR*QS - QZIPN
BombJack[617]=EKIZKPH-R-Q1 - QANMX
BoulderDash[639]=K1I2C3C4F5E6H_R-ASQV Q OKXCV
ChuckieEgg[958]=DRQS1H^+HA^+ARS - 2W90M!
Cobra[996]=E1K2I3C4D7HNR*Q3 - QAOPM
Cyclone[1206]=K2I3K4C5AH+GQ6 M 1QOPXN
Deathchase[1303]=K2E1Q1 - 9810M
EnduroRacer[1628]=HHR*ARQ_ - 43125 QAOP_
EricAndTheFloaters[1639]=Q_:K - WXAD_
Fairlight128K[34308]=- - PLQAM_XZ
FantasyWorldDizzy[9335]=AQQ_ - _-ZX! 9-670
GreenBeret[2134]=D1K2C3I4Q4 - 98670Enter
HeadOverHeels[2259]=HS - QAOPMZ_ 89670Z_
HoraceGoesSkiing[2351]=Q0 - QZIP 4312
HungryHorace[2390]=Q0 - QZIP
JetSetWillyII[2595]=HARAQ! - _-OP_
JumpingJack[2658]=HZRZQ! - --$_^
Kane[2673]=QZ - QANMZ 98670
LunarJetman[9372]=E3K4C5Q6 - Q1XCA1
ManicMiner[3012]=HARHQ! - _-OP_ 7-580
Nebulus[3377]=H!RCQC - PLWEC 76580
Pheenix[3609]=EBCAKKQS:B - !!^Z_
RainbowIslands[724]=HPRPAQQ!:!:!:_ S A-KL_
Renegade[4082]=E1S2I3K4D5HSR*Q1 - QAKL_
Robocop[4179]=E1I2K3D4HSR*Q1 - QAKL_
RType[4256]=H^+1R^+2QP - OKQWP_
Saboteur[4293]=KJEKCPQS:1 - AZNM_
Starquake[4873]=K1C2S3E4D6H_Q0 - QAOPM
StopTheExpress[4916]=IJEKQJ - 98670 ;QZAD_E
SuperHangOn[5019]=E1C2I3K4H*Q_ - QAOP_
Tapper[5143]=A^+_QS - QZIPN
TargetRenegade[4087]=HSR*Q1 - QAKL_
Tetris[5212]=Q_:0 - -_IPO
TheAddamsFamily[82]=E1S2C3K4D5HRQ1 - QAOP_
Thrust[5245]=H2R3A1QN - IMASP
TurboEsprit[5461]=ATQ8 M SAJLK
Underwurlde[9446]=E1K2C3I4H!Q0 - REQWTZ
