// important: list must be sorted
// right column text must be shorter than text in left column

const char* es2en[][2] = { 
    {"ABAJO","DOWN"},
    {"ABORTA","ABORT"},
    {"ABORTAR","ABORT"},
    {"ARRIBA","UP"},
    {"BOMBA","BOMB"},
    {"COGER","PICK"},
    {"COMENZAR","START"},
    {"CONTROLES","CONTROLS"},
    {"CURSORES","CURSOR"},
    {"DEFINIR","DEFINE"},
    {"DERECHA","RIGHT"},
    {"DISPARO","FIRE"},
    {"EMPEZAR","START"},
    {"FUEGO","FIRE"},
    {"INSTRUCCIONES","INSTRUCTIONS"},
    {"IZQUIERDA", "LEFT"},
    {"JUEGO","GAME"},
    {"JUGAR","PLAY"},
    {"PAUSA","PAUSE"},
    {"PULSA UNA TECLA", "PRESS ANY KEY"},
    {"REDEFINIR", "DEFINE"},
    {"REINICIA","RESET"},
    {"REINICIAR", "RESET"},
    {"SALTAR","JUMP"},
    {"SALTO","JUMP"},
    {"TECLADO","KEYPAD"}, // ~"KEYBOARD"
    {"TECLAS","KEYS"},
    //{"USAR", "USE"},
    {"VIDAS","LIFES"},
};

const char* it2en[][2] = { 
    {"ANNULLA","ABORT"},
    {"BOMBA","BOMB"},
    {"CONTROLLI","CONTROLS"},
    {"CURSORI","CURSOR"},
    {"DEFINISCI","DEFINE"},
    {"DESTRA","RIGHT"},
    {"FUOCO","FIRE"},
    {"GIOCA","GAME"},
    {"GIOCA","PLAY"},
    {"GIU","DWN"}, // ~"DOWN"
    {"INIZIA","START"},
    {"ISTRUZIONI","TUTORIAL"}, // ~"INSTRUCTIONS"
    {"PAUSA","PAUSE"},
    {"PREMI UN TASO","PRESS ANY KEY"},
    {"RACCOGLI","PICK"},
    {"RIDEFINISCI","DEFINE"},
    {"RIPARTI","RESET"},
    {"SALTA","JUMP"},
    {"SALTO","JUMP"},
    {"SINISTRA","LEFT"},
    {"SPARO","FIRE"},
    {"SU","UP"},
    {"TASTI","KEYS"},
    {"TASTIERA","KEYBOARD"},
    {"USA","USE"},
    {"VITE","LIFE"}, // ~"LIFES"
};

// es+it -> en
const char* any2en[][2] = { 
    {"ABAJO","DOWN"},
    {"ABORTA","ABORT"},
    {"ABORTAR","ABORT"},
    {"ANNULLA","ABORT"},
    {"ARRIBA","UP"},
    {"BOMBA","BOMB"},
    {"BOMBA","BOMB"},
    {"COGER","PICK"},
    {"COMENZAR","START"},
    {"CONTROLES","CONTROLS"},
    {"CONTROLLI","CONTROLS"},
    {"CURSORES","CURSOR"},
    {"CURSORI","CURSOR"},
    {"DEFINIR","DEFINE"},
    {"DEFINISCI","DEFINE"},
    {"DERECHA","RIGHT"},
    {"DESTRA","RIGHT"},
    {"DISPARO","FIRE"},
    {"EMPEZAR","START"},
    {"FUEGO","FIRE"},
    {"FUOCO","FIRE"},
    {"GIOCA","GAME"},
    {"GIOCA","PLAY"},
    {"GIU","DWN"}, // ~"DOWN"
    {"INIZIA","START"},
    {"INSTRUCCIONES","INSTRUCTIONS"},
    {"ISTRUZIONI","TUTORIAL"}, // ~"INSTRUCTIONS"
    {"IZQUIERDA", "LEFT"},
    {"JUEGO","GAME"},
    {"JUGAR","PLAY"},
    {"PAUSA","PAUSE"},
    {"PAUSA","PAUSE"},
    {"PREMI UN TASO","PRESS ANY KEY"},
    {"PULSA UNA TECLA", "PRESS ANY KEY"},
    {"RACCOGLI","PICK"},
    {"REDEFINIR", "DEFINE"},
    {"REINICIA","RESET"},
    {"REINICIAR", "RESET"},
    {"RIDEFINISCI","DEFINE"},
    {"RIPARTI","RESET"},
    {"SALTA","JUMP"},
    {"SALTAR","JUMP"},
    {"SALTO","JUMP"},
    {"SALTO","JUMP"},
    {"SINISTRA","LEFT"},
    {"SPARO","FIRE"},
    {"SU","UP"},
    {"TASTI","KEYS"},
    {"TASTIERA","KEYBOARD"},
    {"TECLADO","KEYPAD"}, // ~"KEYBOARD"
    {"TECLAS","KEYS"},
    {"USA","USE"},
    {"VIDAS","LIFES"},
    {"VITE","LIFE"}, // ~"LIFES"
};
